

platform :ios, '7.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'FMDB', '~> 2.4'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage', '~> 3.7.1'
pod 'UITextView+Placeholder', '~> 1.0.6'
pod 'YYModel', '~> 1.0.2'